services:
  db:
    container_name: employee-management-system
    image: postgres:14.1
    environment:
      POSTGRES_USER: godwin
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - db:/data/employee-management-system
    ports:
      - "5232:5432"
    networks:
      - db
    restart: unless-stopped
#  amigoscode-api:
#    container_name: godwin-api
#    image: godwin/amigoscode-api
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/customer
#    ports:
#      - "4000:4000"
#    networks:
#      - db
#    depends_on:
#      - db
#    restart: unless-stopped
#  amigoscode-react:
#    container_name: godwin-react
#    image: godwin/amigoscode-react
#    build:
#      context: frontend/react
#      args:
#        api_base_url: http://localhost:8088
#    ports:
#      - "3000:5173"
#    depends_on:
#      - amigoscode-api
#    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db: